<html>
   <head>
         <link rel="stylesheet" type="text/css" href="style.css">
	    </head>
	       //Upon clicking edit button next to item, this form is displayed.
	          <body>
		        <header>
			         <?php include 'header.php'; ?>
				       </header>
				             <main>
					              <h2>Todo List</h2>
						               <table>
							                   <ul>
									                  <?php
											  foreach($tasks
											  as
											  $task)
											  :
											  ?>
											                 <tr>
													                   <td>
															                        <li><a
																		href="?listID=<?php
																		echo
																		$task->getID();
																		?>">
																		                        <?php
																					echo
																					$task->getTitle();
																					?>
																					                        </a>
																								                     </li>
																										                       </td>
																												                         //Display
																															 delete
																															 button
																															 to
																															 delete
																															 task.
																															                   <td>
																																	                        <form
																																				action="."
																																				method="post"
																																				>
																																				                        <input
																																							type="hidden"
																																							name="action"
																																							                           value="delete_task">
																																										                           <input
																																													   type="hidden"
																																													   name="listID"
																																													                              value="<?php
																																																      echo
																																																      $task->getID();
																																																      ?>">
																																																                              <input
																																																			      type="submit"
																																																			      value="Delete">
																																																			                           </form>
																																																						                     </td>
																																																								                       //Display
																																																										       edit
																																																										       button
																																																										       to
																																																										       edit
																																																										       task.
																																																										                         <td>
																																																													                      <form
																																																															      action="."
																																																															      method="post"
																																																															      >
																																																															                              <input
																																																																		      type="hidden"
																																																																		      name="action"
																																																																		                                 value="show_edit_form">
																																																																						                         <input
																																																																									 type="hidden"
																																																																									 name="listID"
																																																																									                            value="<?php
																																																																												    echo
																																																																												    $task->getID();
																																																																												    ?>">
																																																																												                            <input
																																																																															    type="submit"
																																																																															    value="Edit">
																																																																															                         </form>
																																																																																		                   </td>
																																																																																				                  </tr>
																																																																																						                 <?php
																																																																																								 endforeach;
																																																																																								 ?>
																																																																																								             </ul>
																																																																																									              </table>
																																																																																										               //Display
																																																																																											       link
																																																																																											       to
																																																																																											       add
																																																																																											       a
																																																																																											       new
																																																																																											       task
																																																																																											       to
																																																																																											       the
																																																																																											       table
																																																																																											       todo_list
																																																																																											                <p><a
																																																																																													href="index.php?action=show_add_form">Create
																																																																																													New
																																																																																													Todo
																																																																																													List</a></p>
																																																																																													         <h2><?php
																																																																																														 echo
																																																																																														 'Todo
																																																																																														 List
																																																																																														 :'.$current_task->getTitle();
																																																																																														 ?></h2>
																																																																																														          //Display
																																																																																															  items
																																																																																															  in
																																																																																															  selected
																																																																																															  task
																																																																																															           <table>
																																																																																																               <tr>
																																																																																																	                   <tr>
																																																																																																			                  <th>Item</th>
																																																																																																					                 <th>Status</th>
																																																																																																							             </tr>
																																																																																																								                 <?php
																																																																																																										 foreach($items
																																																																																																										 as
																																																																																																										 $item)
																																																																																																										 :
																																																																																																										 ?>
																																																																																																										             <tr>
																																																																																																											                    <td><?php
																																																																																																													    echo
																																																																																																													    $item->getItemTitle();
																																																																																																													    ?></td>
																																																																																																													                   <td><?php
																																																																																																															   echo
																																																																																																															   htmlspecialchars($item->getStatus());
																																																																																																															   ?></td>
																																																																																																															                  <td>
																																																																																																																	                    <form
																																																																																																																			    action="."
																																																																																																																			    method="post"
																																																																																																																			    >
																																																																																																																			                         <input
																																																																																																																						 type="hidden"
																																																																																																																						 name="action"
																																																																																																																						                         value="delete_item">
																																																																																																																									                      <input
																																																																																																																											      type="hidden"
																																																																																																																											      name="itemID"
																																																																																																																											                              value="<?php
																																																																																																																														      echo
																																																																																																																														      $item->getItemID();
																																																																																																																														      ?>">
																																																																																																																														                           <input
																																																																																																																																	   type="hidden"
																																																																																																																																	   name="listID"
																																																																																																																																	                           value="<?php
																																																																																																																																				   echo
																																																																																																																																				   $current_task->getID();
																																																																																																																																				   ?>">
																																																																																																																																				                        <input
																																																																																																																																							type="submit"
																																																																																																																																							value="Delete">
																																																																																																																																							                  </form>
																																																																																																																																									                 </td>
																																																																																																																																											                <p><br
																																																																																																																																													/></p>
																																																																																																																																													               <?php
																																																																																																																																														       if
																																																																																																																																														       ($itemID
																																																																																																																																														       ==
																																																																																																																																														       $item->getItemID())
																																																																																																																																														       {
																																																																																																																																														       ?>
																																																																																																																																														                      <label>&nbsp;</label>
																																																																																																																																																                     <td>
																																																																																																																																																		                    //Form
																																																																																																																																																				    to
																																																																																																																																																				    capture
																																																																																																																																																				    all
																																																																																																																																																				    editing
																																																																																																																																																				    done
																																																																																																																																																				    to
																																																																																																																																																				    the
																																																																																																																																																				    selected
																																																																																																																																																				    item.
																																																																																																																																																				                      <form
																																																																																																																																																						      action="."
																																																																																																																																																						      method="post"
																																																																																																																																																						      >
																																																																																																																																																						                           <input
																																																																																																																																																									   type="hidden"
																																																																																																																																																									   name="action"
																																																																																																																																																									   value="edit_item"
																																																																																																																																																									   />
																																																																																																																																																									                        <input
																																																																																																																																																												type="hidden"
																																																																																																																																																												name="itemID"
																																																																																																																																																												                        value="<?php
																																																																																																																																																															echo
																																																																																																																																																															$item->getItemID();
																																																																																																																																																															?>">
																																																																																																																																																															                     <input
																																																																																																																																																																	     type="hidden"
																																																																																																																																																																	     name="listID"
																																																																																																																																																																	                             value="<?php
																																																																																																																																																																				     echo
																																																																																																																																																																				     $current_task->getID();
																																																																																																																																																																				     ?>">
																																																																																																																																																																				                          <input
																																																																																																																																																																							  type="hidden"
																																																																																																																																																																							  name="old_item_title"
																																																																																																																																																																							                          value="<?php
																																																																																																																																																																										  echo
																																																																																																																																																																										  $item->getItemTitle();
																																																																																																																																																																										  ?>">
																																																																																																																																																																										                       <input
																																																																																																																																																																												       type="hidden"
																																																																																																																																																																												       name="old_status"
																																																																																																																																																																												                               value="<?php
																																																																																																																																																																															       echo
																																																																																																																																																																															       $item->getStatus();
																																																																																																																																																																															       ?>">
																																																																																																																																																																															                            <label>Item
																																																																																																																																																																																		    Title:</label>
																																																																																																																																																																																		                         <input
																																																																																																																																																																																					 type="text"
																																																																																																																																																																																					 name="item_title"
																																																																																																																																																																																					 placeholder="<?php
																																																																																																																																																																																					 echo
																																																																																																																																																																																					 $item->getItemTitle();
																																																																																																																																																																																					 ?>">
																																																																																																																																																																																					                      <label>&nbsp;</label>
																																																																																																																																																																																							                           <label>Status:</label>
																																																																																																																																																																																										                        <select
																																																																																																																																																																																													name="status">
																																																																																																																																																																																													                       <option
																																																																																																																																																																																															       value="Not_set">Not
																																																																																																																																																																																															       set</option>
																																																																																																																																																																																															                      		   <option
																																																																																																																																																																																																			   value="Not_started">Not
																																																																																																																																																																																																			   started</option>
																																																																																																																																																																																																			                  		   <option
																																																																																																																																																																																																							   value="25%_done">25%
																																																																																																																																																																																																							   done</option>
																																																																																																																																																																																																							                          <option
																																																																																																																																																																																																										  value="50%_done">50%
																																																																																																																																																																																																										  done</option>
																																																																																																																																																																																																										                         <option
																																																																																																																																																																																																													 value="75%_done">75%
																																																																																																																																																																																																													 done</option>
																																																																																																																																																																																																													                        <option
																																																																																																																																																																																																																value="complete">done</option>
																																																																																																																																																																																																																                     </select>
																																																																																																																																																																																																																		                          <label>&nbsp;</label>
																																																																																																																																																																																																																					                       <input
																																																																																																																																																																																																																							       type="submit"
																																																																																																																																																																																																																							       value="Done">
																																																																																																																																																																																																																							                            <br>
																																																																																																																																																																																																																										                      </form>
																																																																																																																																																																																																																												                     </td>
																																																																																																																																																																																																																														                    <?php
																																																																																																																																																																																																																																    }
																																																																																																																																																																																																																																    else
																																																																																																																																																																																																																																    {
																																																																																																																																																																																																																																    ?>
																																																																																																																																																																																																																																                   <td>
																																																																																																																																																																																																																																		                  //For
																																																																																																																																																																																																																																				  all
																																																																																																																																																																																																																																				  tasks
																																																																																																																																																																																																																																				  other
																																																																																																																																																																																																																																				  than
																																																																																																																																																																																																																																				  selected
																																																																																																																																																																																																																																				  item,
																																																																																																																																																																																																																																				  display
																																																																																																																																																																																																																																				  edit
																																																																																																																																																																																																																																				  button.
																																																																																																																																																																																																																																				                    <form
																																																																																																																																																																																																																																						    action="."
																																																																																																																																																																																																																																						    method="post"
																																																																																																																																																																																																																																						    >
																																																																																																																																																																																																																																						                         <input
																																																																																																																																																																																																																																									 type="hidden"
																																																																																																																																																																																																																																									 name="action"
																																																																																																																																																																																																																																									                         value="show_edit_form">
																																																																																																																																																																																																																																												                      <input
																																																																																																																																																																																																																																														      type="hidden"
																																																																																																																																																																																																																																														      name="itemID"
																																																																																																																																																																																																																																														                              value="<?php
																																																																																																																																																																																																																																																	      echo
																																																																																																																																																																																																																																																	      $item->getItemID();
																																																																																																																																																																																																																																																	      ?>">
																																																																																																																																																																																																																																																	                           <input
																																																																																																																																																																																																																																																				   type="hidden"
																																																																																																																																																																																																																																																				   name="listID"
																																																																																																																																																																																																																																																				                           value="<?php
																																																																																																																																																																																																																																																							   echo
																																																																																																																																																																																																																																																							   $current_task->getID();
																																																																																																																																																																																																																																																							   ?>">
																																																																																																																																																																																																																																																							                        <input
																																																																																																																																																																																																																																																										type="submit"
																																																																																																																																																																																																																																																										value="Edit">
																																																																																																																																																																																																																																																										                  </form>
																																																																																																																																																																																																																																																												                 </td>
																																																																																																																																																																																																																																																														                <?php
																																																																																																																																																																																																																																																																}
																																																																																																																																																																																																																																																																?>
																																																																																																																																																																																																																																																																            </tr>
																																																																																																																																																																																																																																																																	                <?php
																																																																																																																																																																																																																																																																			endforeach;
																																																																																																																																																																																																																																																																			?>
																																																																																																																																																																																																																																																																			         </table>
																																																																																																																																																																																																																																																																				           //display
																																																																																																																																																																																																																																																																					   Add_Todo
																																																																																																																																																																																																																																																																					   button
																																																																																																																																																																																																																																																																					   to
																																																																																																																																																																																																																																																																					   add
																																																																																																																																																																																																																																																																					   more
																																																																																																																																																																																																																																																																					   items
																																																																																																																																																																																																																																																																					   to
																																																																																																																																																																																																																																																																					   the
																																																																																																																																																																																																																																																																					   selected
																																																																																																																																																																																																																																																																					   task.
																																																																																																																																																																																																																																																																					            <form
																																																																																																																																																																																																																																																																						    action="."
																																																																																																																																																																																																																																																																						    method="post"
																																																																																																																																																																																																																																																																						    >
																																																																																																																																																																																																																																																																						             <input
																																																																																																																																																																																																																																																																							     type="hidden"
																																																																																																																																																																																																																																																																							     name="action"
																																																																																																																																																																																																																																																																							                 value="show_add_item_form">
																																																																																																																																																																																																																																																																									          <input
																																																																																																																																																																																																																																																																										  type="hidden"
																																																																																																																																																																																																																																																																										  name="listID"
																																																																																																																																																																																																																																																																										              value="<?php
																																																																																																																																																																																																																																																																											      echo
																																																																																																																																																																																																																																																																											      $current_task->getID();
																																																																																																																																																																																																																																																																											      ?>">
																																																																																																																																																																																																																																																																											               <input
																																																																																																																																																																																																																																																																												       type="submit"
																																																																																																																																																																																																																																																																												       id="add-button"
																																																																																																																																																																																																																																																																												       value="Add_Todo">
																																																																																																																																																																																																																																																																												             </main>
																																																																																																																																																																																																																																																																													           <?php
																																																																																																																																																																																																																																																																														   include
																																																																																																																																																																																																																																																																														   'footer.php';
																																																																																																																																																																																																																																																																														   ?>
																																																																																																																																																																																																																																																																														      </body>
																																																																																																																																																																																																																																																																														      </html>

