<html>
   <head>
         <link rel="stylesheet" type="text/css" href="style.css">
	    </head>
	       //Upon clicking Create New List link to add task, this form is displayed.
	          <body>
		        <header>
			         <?php include 'header.php'; ?>
				       </header>
				             <main>
					              <h2>Todo List</h2>
						               <table>
							                   <ul>
									                  <?php
											  foreach($tasks
											  as
											  $task)
											  :
											  ?>
											                 <tr>
													                   <td>
															                        <li><a
																		href="?listID=<?php
																		echo
																		$task->getID();
																		?>">
																		                        <?php
																					echo
																					$task->getTitle();
																					?>
																					                        </a>
																								                     </li>
																										                       </td>
																												                          //Display
																															  delete
																															  button
																															  to
																															  delete
																															  task.
																															                    <td>
																																	                         <form
																																				 action="."
																																				 method="post"
																																				 >
																																				                         <input
																																							 type="hidden"
																																							 name="action"
																																							                            value="delete_task">
																																										                            <input
																																													    type="hidden"
																																													    name="listID"
																																													                               value="<?php
																																																       echo
																																																       $task->getID();
																																																       ?>">
																																																                               <input
																																																			       type="submit"
																																																			       value="Delete">
																																																			                            </form>
																																																						                      </td>
																																																								                         //Display
																																																											 edit
																																																											 button
																																																											 to
																																																											 edit
																																																											 task.
																																																											                   <td>
																																																													                        <form
																																																																action="."
																																																																method="post"
																																																																>
																																																																                        <input
																																																																			type="hidden"
																																																																			name="action"
																																																																			                           value="show_edit_form">
																																																																						                           <input
																																																																									   type="hidden"
																																																																									   name="listID"
																																																																									                              value="<?php
																																																																												      echo
																																																																												      $task->getID();
																																																																												      ?>">
																																																																												                              <input
																																																																															      type="submit"
																																																																															      value="Edit">
																																																																															                           </form>
																																																																																		                     </td>
																																																																																				                    </tr>
																																																																																						                   <?php
																																																																																								   endforeach;
																																																																																								   ?>
																																																																																								               </ul>
																																																																																									                </table>
																																																																																											         //Display
																																																																																												 link
																																																																																												 to
																																																																																												 add
																																																																																												 a
																																																																																												 new
																																																																																												 task
																																																																																												 to
																																																																																												 the
																																																																																												 table
																																																																																												 todo_list
																																																																																												          <p><a
																																																																																													  href="index.php?action=show_add_form">Create
																																																																																													  New
																																																																																													  Todo
																																																																																													  List</a></p>
																																																																																													           //Display
																																																																																														   all
																																																																																														   items
																																																																																														   in
																																																																																														   the
																																																																																														   selected
																																																																																														   task
																																																																																														   from
																																																																																														   table
																																																																																														   todo_item
																																																																																														   if
																																																																																														   not
																																																																																														   empty
																																																																																														            <?php
																																																																																															    if
																																																																																															    ($items
																																																																																															    !=
																																																																																															    NULL)
																																																																																															    {
																																																																																															    ?>   
																																																																																															             <h2><?php
																																																																																																     echo
																																																																																																     'Todo
																																																																																																     List
																																																																																																     :'.$current_task->getTitle();
																																																																																																     ?></h2>
																																																																																																              <table>
																																																																																																	                  <tr>
																																																																																																			              <tr>
																																																																																																				                     <th>Item</th>
																																																																																																						                    <th>Status</th>
																																																																																																								                </tr>
																																																																																																										            <?php
																																																																																																											    foreach($items
																																																																																																											    as
																																																																																																											    $item)
																																																																																																											    :
																																																																																																											    ?>
																																																																																																											                <tr>
																																																																																																													               <td><?php
																																																																																																														       echo
																																																																																																														       $item->getItemTitle();
																																																																																																														       ?></td>
																																																																																																														                      <td><?php
																																																																																																																      echo
																																																																																																																      htmlspecialchars($item->getStatus());
																																																																																																																      ?></td>
																																																																																																																                     
																																																																																																																		                     //Display
																																																																																																																				     edit
																																																																																																																				     button
																																																																																																																				     to
																																																																																																																				     edit
																																																																																																																				     item
																																																																																																																				                    <td>
																																																																																																																						                      <form
																																																																																																																								      action="."
																																																																																																																								      method="post"
																																																																																																																								      >
																																																																																																																								                           <input
																																																																																																																											   type="hidden"
																																																																																																																											   name="action"
																																																																																																																											                           value="show_edit_item_form">
																																																																																																																														                        <input
																																																																																																																																	type="hidden"
																																																																																																																																	name="itemID"
																																																																																																																																	                        value="<?php
																																																																																																																																				echo
																																																																																																																																				$item->getItemID();
																																																																																																																																				?>">
																																																																																																																																				                     <input
																																																																																																																																						     type="hidden"
																																																																																																																																						     name="listID"
																																																																																																																																						                             value="<?php
																																																																																																																																									     echo
																																																																																																																																									     $current_task->getID();
																																																																																																																																									     ?>">
																																																																																																																																									                          <input
																																																																																																																																												  type="submit"
																																																																																																																																												  value="Edit">
																																																																																																																																												                    </form>
																																																																																																																																														                   </td>
																																																																																																																																																               </tr>
																																																																																																																																																	                   <?php
																																																																																																																																																			   endforeach;
																																																																																																																																																			   ?>
																																																																																																																																																			            </table>
																																																																																																																																																				             //Form
																																																																																																																																																					     to
																																																																																																																																																					     capture
																																																																																																																																																					     New
																																																																																																																																																					     Item
																																																																																																																																																					     details.
																																																																																																																																																					              <form
																																																																																																																																																						      action="."
																																																																																																																																																						      method="post"
																																																																																																																																																						      >
																																																																																																																																																						                  <input
																																																																																																																																																								  type="hidden"
																																																																																																																																																								  name="action"
																																																																																																																																																								  value="add_item"
																																																																																																																																																								  />
																																																																																																																																																								              <input
																																																																																																																																																									      type="hidden"
																																																																																																																																																									      name="listID"
																																																																																																																																																									                     value="<?php
																																																																																																																																																											     echo
																																																																																																																																																											     $current_task->getID();
																																																																																																																																																											     ?>">
																																																																																																																																																											                 <label>New
																																																																																																																																																													 Item
																																																																																																																																																													 Title:</label>
																																																																																																																																																													             <input
																																																																																																																																																														     type="text"
																																																																																																																																																														     name="item_title"
																																																																																																																																																														     placeholder="New
																																																																																																																																																														     Item
																																																																																																																																																														     Title">
																																																																																																																																																														                 <label>Status:</label>
																																																																																																																																																																             <select
																																																																																																																																																																	     name="status">
																																																																																																																																																																	                    <option
																																																																																																																																																																			    value="Not_set">Not
																																																																																																																																																																			    set</option>
																																																																																																																																																																			                   <option
																																																																																																																																																																					   value="Not_started">Not
																																																																																																																																																																					   started</option>
																																																																																																																																																																					                  <option
																																																																																																																																																																							  value="25%_done">25%
																																																																																																																																																																							  done</option>
																																																																																																																																																																							                 <option
																																																																																																																																																																									 value="50%_done">50%
																																																																																																																																																																									 done</option>
																																																																																																																																																																									                <option
																																																																																																																																																																											value="75%_done">75%
																																																																																																																																																																											done</option>
																																																																																																																																																																											               <option
																																																																																																																																																																												       value="complete">done</option>
																																																																																																																																																																												                   </select>
																																																																																																																																																																														               <input
																																																																																																																																																																															       type="submit"
																																																																																																																																																																															       id="add-button"
																																																																																																																																																																															       value="Add">
																																																																																																																																																																															                   <br>
																																																																																																																																																																																	            </form>
																																																																																																																																																																																		             //
																																																																																																																																																																																			     If
																																																																																																																																																																																			     items
																																																																																																																																																																																			     are
																																																																																																																																																																																			     empty,
																																																																																																																																																																																			     display
																																																																																																																																																																																			     Add
																																																																																																																																																																																			     Item
																																																																																																																																																																																			     Form
																																																																																																																																																																																			     to
																																																																																																																																																																																			     add
																																																																																																																																																																																			     more
																																																																																																																																																																																			     items
																																																																																																																																																																																			     to
																																																																																																																																																																																			     the
																																																																																																																																																																																			     selected
																																																																																																																																																																																			     task.
																																																																																																																																																																																			              <?php
																																																																																																																																																																																				      }
																																																																																																																																																																																				      else
																																																																																																																																																																																				      if
																																																																																																																																																																																				      ($tasks
																																																																																																																																																																																				      !=
																																																																																																																																																																																				      NULL){
																																																																																																																																																																																				      ?>
																																																																																																																																																																																				               <h2><?php
																																																																																																																																																																																					       echo
																																																																																																																																																																																					       'Items
																																																																																																																																																																																					       In
																																																																																																																																																																																					       Todo
																																																																																																																																																																																					       List
																																																																																																																																																																																					       :'.$current_task->getTitle();
																																																																																																																																																																																					       ?></h2>
																																																																																																																																																																																					                 //Form
																																																																																																																																																																																							 to
																																																																																																																																																																																							 capture
																																																																																																																																																																																							 New
																																																																																																																																																																																							 Item
																																																																																																																																																																																							 details.
																																																																																																																																																																																							          <form
																																																																																																																																																																																								  action="."
																																																																																																																																																																																								  method="post"
																																																																																																																																																																																								  >
																																																																																																																																																																																								              <input
																																																																																																																																																																																									      type="hidden"
																																																																																																																																																																																									      name="action"
																																																																																																																																																																																									      value="add_item"
																																																																																																																																																																																									      />
																																																																																																																																																																																									                  <input
																																																																																																																																																																																											  type="hidden"
																																																																																																																																																																																											  name="listID"
																																																																																																																																																																																											                 value="<?php
																																																																																																																																																																																													 echo
																																																																																																																																																																																													 $current_task->getID();
																																																																																																																																																																																													 ?>">
																																																																																																																																																																																													             <label>New
																																																																																																																																																																																														     Item
																																																																																																																																																																																														     Title:</label>
																																																																																																																																																																																														                 <input
																																																																																																																																																																																																 type="text"
																																																																																																																																																																																																 name="item_title"
																																																																																																																																																																																																 placeholder="New
																																																																																																																																																																																																 Item
																																																																																																																																																																																																 Title">
																																																																																																																																																																																																             <label>Status:</label>
																																																																																																																																																																																																	                 <select
																																																																																																																																																																																																			 name="status">
																																																																																																																																																																																																			                <option
																																																																																																																																																																																																					value="Not_set">Not
																																																																																																																																																																																																					set</option>
																																																																																																																																																																																																					               <option
																																																																																																																																																																																																						       value="Not_started">Not
																																																																																																																																																																																																						       started</option>
																																																																																																																																																																																																						                      <option
																																																																																																																																																																																																								      value="25%_done">25%
																																																																																																																																																																																																								      done</option>
																																																																																																																																																																																																								                     <option
																																																																																																																																																																																																										     value="50%_done">50%
																																																																																																																																																																																																										     done</option>
																																																																																																																																																																																																										                    <option
																																																																																																																																																																																																												    value="75%_done">75%
																																																																																																																																																																																																												    done</option>
																																																																																																																																																																																																												                   <option
																																																																																																																																																																																																														   value="complete">done</option>
																																																																																																																																																																																																														               </select>
																																																																																																																																																																																																															                   <input
																																																																																																																																																																																																																	   type="submit"
																																																																																																																																																																																																																	   id="add-button"
																																																																																																																																																																																																																	   value="Add">
																																																																																																																																																																																																																	               <br>
																																																																																																																																																																																																																		                </form>
																																																																																																																																																																																																																				         <?php
																																																																																																																																																																																																																					 }
																																																																																																																																																																																																																					 ?>
																																																																																																																																																																																																																					       </main>
																																																																																																																																																																																																																					             <?php
																																																																																																																																																																																																																						     include
																																																																																																																																																																																																																						     'footer.php';
																																																																																																																																																																																																																						     ?>
																																																																																																																																																																																																																						        </body>
																																																																																																																																																																																																																							</html>
