<html>
   <head>
         <link rel="stylesheet" type="text/css" href="style.css">
	    </head>
	       //Upon clicking edit button next to task, this form is displayed.
	          <body>
		        <header>
			         <?php include 'header.php'; ?>
				       </header>
				             <main>
					              <h2>Todo List</h2>
						               <table>
							                   <ul>
									                  <?php
											  foreach($tasks
											  as
											  $task)
											  :
											  ?>
											                 <tr>
													                   <td>
															                        <li><a
																		href="?listID=<?php
																		echo
																		$task->getID();
																		?>">
																		                        <?php
																					echo
																					$task->getTitle();
																					?>
																					                        </a>
																								                     </li>
																										                       </td>
																												                         //Display
																															 delete
																															 button
																															 to
																															 delete
																															 task.
																															                   <td>
																																	                        <form
																																				action="."
																																				method="post"
																																				>
																																				                        <input
																																							type="hidden"
																																							name="action"
																																							                           value="delete_task">
																																										                           <input
																																													   type="hidden"
																																													   name="listID"
																																													                              value="<?php
																																																      echo
																																																      $task->getID();
																																																      ?>">
																																																                              <input
																																																			      type="submit"
																																																			      value="Delete">
																																																			                           </form>
																																																						                     </td>
																																																								                       //Form
																																																										       to
																																																										       capture
																																																										       all
																																																										       editing
																																																										       done
																																																										       to
																																																										       the
																																																										       selected
																																																										       task.
																																																										                         <?php
																																																													 if
																																																													 ($listID
																																																													 ==
																																																													 $task->getID())
																																																													 {
																																																													 ?>
																																																													                   <td>
																																																															                        <form
																																																																		action="."
																																																																		method="post"
																																																																		>
																																																																		                        <input
																																																																					type="hidden"
																																																																					name="action"
																																																																					value="edit_task"
																																																																					/>
																																																																					                        <input
																																																																								type="hidden"
																																																																								name="listID"
																																																																								                           value="<?php
																																																																											   echo
																																																																											   $task->getID();
																																																																											   ?>
																																																																											   ">
																																																																											                           <input
																																																																														   type="hidden"
																																																																														   name="old_title"
																																																																														                              value="<?php
																																																																																	      echo
																																																																																	      $task->getTitle();
																																																																																	      ?>">
																																																																																	                              <input
																																																																																				      type="text"
																																																																																				      name="title"
																																																																																				      placeholder="<?php
																																																																																				      echo
																																																																																				      $task->getTitle();
																																																																																				      ?>">
																																																																																				                              <label>&nbsp;</label>
																																																																																							                              <input
																																																																																										      type="submit"
																																																																																										      value="Done">
																																																																																										                              <br>
																																																																																													                           </form>
																																																																																																                     </td>
																																																																																																		         				//For
																																																																																																							all
																																																																																																							tasks
																																																																																																							other
																																																																																																							than
																																																																																																							selected
																																																																																																							task,
																																																																																																							display
																																																																																																							edit
																																																																																																							button.
																																																																																																							                  <?php
																																																																																																									  }
																																																																																																									  else
																																																																																																									  {
																																																																																																									  ?>
																																																																																																									                    <td>
																																																																																																											                         <form
																																																																																																														 action="."
																																																																																																														 method="post"
																																																																																																														 >
																																																																																																														                         <input
																																																																																																																	 type="hidden"
																																																																																																																	 name="action"
																																																																																																																	                            value="show_edit_form">
																																																																																																																				                            <input
																																																																																																																							    type="hidden"
																																																																																																																							    name="listID"
																																																																																																																							                               value="<?php
																																																																																																																										       echo
																																																																																																																										       $task->getID();
																																																																																																																										       ?>">
																																																																																																																										                               <input
																																																																																																																													       type="submit"
																																																																																																																													       value="Edit">
																																																																																																																													                            </form>
																																																																																																																																                      </td>
																																																																																																																																		                        <?php
																																																																																																																																					}
																																																																																																																																					?>
																																																																																																																																					               </tr>
																																																																																																																																						                      <?php
																																																																																																																																								      endforeach;
																																																																																																																																								      ?>
																																																																																																																																								                  </ul>
																																																																																																																																										           </table>
																																																																																																																																											            //Display
																																																																																																																																												    link
																																																																																																																																												    to
																																																																																																																																												    add
																																																																																																																																												    a
																																																																																																																																												    new
																																																																																																																																												    task
																																																																																																																																												    to
																																																																																																																																												    the
																																																																																																																																												    table
																																																																																																																																												    todo_list
																																																																																																																																												             <p><a
																																																																																																																																													     href="index.php?action=show_add_form">Create
																																																																																																																																													     New
																																																																																																																																													     Todo
																																																																																																																																													     List</a></p>
																																																																																																																																													              
																																																																																																																																														            </main>
																																																																																																																																															          <?php
																																																																																																																																																  include
																																																																																																																																																  'footer.php';
																																																																																																																																																  ?>
																																																																																																																																																     </body>
																																																																																																																																																     </html>
