<html>
   <head>
         //add the stylesheet for the application
	       <link rel="stylesheet" type="text/css" href="style.css">
	          </head>
		     <body>
		           <header>
			            <?php include 'header.php'; ?>
				          </header>
					        <main>
						         <h2>Todo List</h2>
							          <table>
								              <ul>
									                     //
											     display
											     all
											     the
											     tasks
											     in
											     the
											     table
											     todo_list 
											                    <?php
													    foreach($tasks
													    as
													    $task)
													    :
													    ?>
													                   <tr>
															                     <td>
																	                          <li><a
																				  href="?listID=<?php
																				  echo
																				  $task->getID();
																				  ?>">
																				                          <?php
																							  echo
																							  $task->getTitle();
																							  ?>
																							                          </a>
																										                       </li>
																												                         </td>
																															                  </tr>
																																	                 </ul>
																																			             </table>
																																				                 
																																						               //Form
																																							       to
																																							       capture
																																							       New
																																							       Task
																																							       title.
																																							                <form
																																									action="."
																																									method="post"
																																									>
																																									            <input
																																										    type="hidden"
																																										    name="action"
																																										    value="add_task"
																																										    />
																																										                <label>New
																																												Title:</label>
																																												            <input
																																													    type="text"
																																													    name="title"
																																													    placeholder="New
																																													    Title">
																																													                <label>&nbsp;</label>
																																															            <input
																																																    type="submit"
																																																    id="add-button"
																																																    value="Add">
																																																                <br>
																																																		         </form>
																																																			           </main>
																																																				         <?php
																																																					 include
																																																					 'footer.php';
																																																					 ?>
																																																					    </body>
																																																					    </html>
