<html>
   <head>
         <link rel="stylesheet" type="text/css" href="style.css">
	    </head>
	       //Upon clicking Create New List link to add task, this form is displayed.
	          <body>
		        <header>
			         <?php include 'header.php'; ?>
				       </header>
				             <main>
					              <h2>Todo List</h2>
						               <table>
							                   <ul>
									                  <?php
											  foreach($tasks
											  as
											  $task)
											  :
											  ?>
											                 <tr>
													                   <td>
															                        <li><a
																		href="?listID=<?php
																		echo
																		$task->getID();
																		?>">
																		                        <?php
																					echo
																					$task->getTitle();
																					?>
																					                        </a>
																								                     </li>
																										                       </td>
																												                         //Display
																															 delete
																															 buttton
																															 to
																															 delete
																															 task.
																															                   <td>
																																	                        <form
																																				action="."
																																				method="post"
																																				>
																																				                        <input
																																							type="hidden"
																																							name="action"
																																							                           value="delete_task">
																																										                           <input
																																													   type="hidden"
																																													   name="listID"
																																													                              value="<?php
																																																      echo
																																																      $task->getID();
																																																      ?>">
																																																                              <input
																																																			      type="submit"
																																																			      value="Delete">
																																																			                           </form>
																																																						                     </td>
																																																								                       //Display
																																																										       edit
																																																										       button
																																																										       to
																																																										       edit
																																																										       task.
																																																										                         <td>
																																																													                      <form
																																																															      action="."
																																																															      method="post"
																																																															      >
																																																															                              <input
																																																																		      type="hidden"
																																																																		      name="action"
																																																																		                                 value="show_edit_form">
																																																																						                         <input
																																																																									 type="hidden"
																																																																									 name="listID"
																																																																									                            value="<?php
																																																																												    echo
																																																																												    $task->getID();
																																																																												    ?>">
																																																																												                            <input
																																																																															    type="submit"
																																																																															    value="Edit">
																																																																															                         </form>
																																																																																		                   </td>
																																																																																				                  </tr>
																																																																																						                 <?php
																																																																																								 endforeach;
																																																																																								 ?>
																																																																																								             </ul>
																																																																																									              </table>
																																																																																										               //Form
																																																																																											       to
																																																																																											       capture
																																																																																											       New
																																																																																											       Task
																																																																																											       title.
																																																																																											                <form
																																																																																													action="."
																																																																																													method="post"
																																																																																													>
																																																																																													            <input
																																																																																														    type="hidden"
																																																																																														    name="action"
																																																																																														    value="add_task"
																																																																																														    />
																																																																																														                <label>New
																																																																																																Title:</label>
																																																																																																            <input
																																																																																																	    type="text"
																																																																																																	    name="title"
																																																																																																	    placeholder="New
																																																																																																	    Title">
																																																																																																	                <label>&nbsp;</label>
																																																																																																			            <input
																																																																																																				    type="submit"
																																																																																																				    id="add-button"
																																																																																																				    value="Add">
																																																																																																				                <br>
																																																																																																						         </form>
																																																																																																							       </main>
																																																																																																							             <?php
																																																																																																								     include
																																																																																																								     'footer.php';
																																																																																																								     ?>
																																																																																																								        </body>
																																																																																																									</html>
